version: '3'
services:
   annotate:
      build: .
      ports:
         - "8888:${ANNOTATE_PORT}"
      volumes:
         - ${PWD}/src:/src
         - ${PWD}/save:/save
         - ${PWD}/cache:/cache
         - ${PWD}/config:/config
         - ${PWD}:/git
         - /home/mayajas/Documents/project-00-7t-pipeline-dev/results:/data
      environment:
        - DOCKER_STACKS_JUPYTER_CMD=notebook
